step1:
	npm init -y
	npm install typescript ts-node
	npm install --save @types/express express body-parser mongoose nodemon
	mkdir lib
	mkdir lib/config
	touch lib/config/app.ts
	touch lib/server.ts
	mkdir lib/controllers
	mkdir lib/modules
	mkdir lib/routes
	touch lib/environment.ts
	